export const ADD_MOVIE_TO_WATCHLIST='ADD_MOVIE_TO_WATCHLIST';
export const REMOV_MOVIE_FROM_WATCHLIST=' REMOV_MOVIE_FROM_WATCHLIST';
export const ADD_MOVIE_TO_WATCHED='ADD_MOVIE_TO_WATCHED';
export const REMOV_MOVIE_FROM_WATCHED='REMOV_MOVIE_FROM_WATCHED';
export const MOVE_TO_WATCHLIST='MOVE_TO_WATCHLIST';
